name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@main
        with:
          otp-version: "27.0.1"
          elixir-version: "1.17"
          version-type: strict

      - run: mix ci
