name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      # TODO: Remove on Req 1.0
      REQ_NOWARN_OUTPUT: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.13"
              otp: "24.3.4.10"
          - pair:
              elixir: "1.17"
              otp: "27.0.1"
            lint: lint
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@main
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}
          version-type: strict

      - uses: actions/cache@v4
        with:
          path: deps
          # ezstd and brotli are compiling native objects to deps/x/_build, not _build,
          # so we need to cache per OTP
          key: mix-otp-${{ matrix.pair.otp }}-deps-${{ hashFiles('**/mix.lock') }}

      - run: mix ci
